R-Lum/Luminescence

R/calc_CobbleDoseRate.R
Hi, I've changed the U beta attenuation coefficients. Thanks
=> calc_CobbleDoseRate

R/read_PSL2R.R, tests/testthat/test_read_PSL2R.R
Fixes #127 and adds some tests to bring coverage to 100% (#121).
=> Improve input validation and complete coverage in read_PSL2R.R

R/plot_GrowthCurve.R, tests/testthat/test_plot_GrowthCurve.R
An error message contradicted the code and the documentation. This also removes the awkward assignment mentioned in #138.
=> Fix error message and awkward code in plot_GrowthCurve()

tests/testthat/test_PSL2RisoeBINfiledata.R, tests/testthat/test_apply_EfficiencyCorrection.R, tests/testthat/test_calc_Lamothe2003.R, tests/testthat/test_combine_De_Dr.R, tests/testthat/test_convert_Wavelength2Energy.R, tests/testthat/test_convert_XYSG2CSV.R, tests/testthat/test_read_Daybreak2R.R
Adds more tests for these files:
* PSL2RisoeBINfiledata.R
* apply_EfficiencyCorrection.R
* calc_Lamothe2003.R
* combine_De_Dr.R
* convert_Wavelength2Energy.R
* convert_XYSG2CSV.R
* read_Daybreak2R.R
Part of #121.
=> More coverage

NEWS.Rmd, R/read_Daybreak2R.R, tests/testthat/test_read_Daybreak2R.R
=> Better detection of non-ASCII files in read_Daybreak2R.R

R/analyse_SAR.CWOSL.R, R/calc_AverageDose.R, R/calc_Huntley2006.R, R/fit_EmissionSpectra.R, R/fit_SurfaceExposure.R, man/calc_AverageDose.Rd, tests/testthat/test_analyse_SAR.CWOSL.R, tests/testthat/test_calc_AverageDose.R, tests/testthat/test_calc_Huntley2006.R, tests/testthat/test_combine_De_Dr.R, tests/testthat/test_fit_EmissionSpectra.R, tests/testthat/test_fit_SurfaceExposure.R, tests/testthat/test_read_Daybreak2R.R
Concerns these files (part of #121):
* analyse_SAR.CWOSL.R
* calc_AverageDose.R
* calc_Huntley2006.R
* fit_EmissionSpectra.R
* fit_SurfaceExposure.R
* read_Daybreak2R.R
This also restores the graphical parameters at the end of `test_combine_De_Dr.R` and allows to reinstate a plot in `test_fit_EmissionSpectra.R` that used to fail, fixing #161.
=> More coverage and fixes

NEWS.Rmd, R/analyse_baSAR.R, tests/testthat/test_analyse_baSAR.R
Fixes #183 and adds a test for it.
=> Check that there are records in an object before subsetting from them

R/analyse_FadingMeasurement.R, R/fit_OSLLifeTimes.R, R/fit_ThermalQuenching.R, R/read_Daybreak2R.R, R/read_SPE2R.R, tests/testthat/test_analyse_FadingMeasurement.R, tests/testthat/test_fit_OSLLifeTimes.R, tests/testthat/test_read_SPE2R.R
This concerns these files (part of #121):
* R/analyse_FadingMeasurement.R
* R/fit_OSLLifeTimes.R
* R/read_SPE2R.R
=> Some more coverage

R/plot_AbanicoPlot.R, R/plot_RLum.Results.R, R/plot_RadialPlot.R, tests/testthat/test_plot_Functions.R, tests/testthat/test_plot_RLum.Results.R, tests/testthat/test_plot_RadialPlot.R
This adds coverage for these files (part of #121):
- plot_RadialPlot()
- plot_RLum.Results.R.
This also removes some code in `plot_RadialPlot.R` that is unreachable, thus also helping with coverage.
=> Some more coverage and removal of unreachable code

NEWS.Rmd, R/plot_KDE.R, man/plot_KDE.Rd, tests/testthat/test_plot_KDE.R
=> Support vectors and single-column data frames in plot_KDE()

R/plot_KDE.R, tests/testthat/test_plot_KDE.R
=> Add a check for zero-row input data to plot_KDE()

R/calc_MinDose.R, tests/testthat/test_calc_MinDose.R
=> Better validation of the par argument of calc_MinDose()

R/analyse_SAR.TL.R
=> Silence notes raised by R CMD check

NEWS.Rmd, R/Analyse_SAR.OSLdata.R, man/Analyse_SAR.OSLdata.Rd, tests/testthat/test_Analyse_SAROSLdata.R
=> Deprecate Analyse_SAR.OSLdata() in favour of analyse_SAR.CWOSL()

R/internals_RLum.R, R/plot_RLum.Analysis.R, R/plot_RLum.Data.Curve.R, tests/testthat/test_internals.R, tests/testthat/test_plot_RLum.Analysis.R, tests/testthat/test_plot_RLum.Data.Curve.R
=> Extract curve normalisation code into an internal helper function

R/internals_Thermochronometry.R, tests/testthat/_snaps/internals_Thermochronometry.md, tests/testthat/setup.R, tests/testthat/test_internals_Thermochronometry.R
This adds tests for `.import_ThermochronometryData()` using an Excel data file.
=> Complete coverage for .import_ThermochronometryData.R

R/analyse_portableOSL.R, R/plot_RLum.Analysis.R, R/use_DRAC.R, R/write_R2BIN.R, tests/testthat/test_analyse_IRSAR.RF.R, tests/testthat/test_analyse_SAR.TL.R, tests/testthat/test_analyse_baSAR.R, tests/testthat/test_analyse_portableOSL.R, tests/testthat/test_plot_NRt.R, tests/testthat/test_plot_RLum.Analysis.R, tests/testthat/test_use_DRAC.R, tests/testthat/test_write_R2BIN.R
Together with some trivial code cleanup.
=> Some small coverage increases

R/RLum.Analysis-class.R, R/RLum.Data.Image-class.R, R/RLum.Data.Spectrum-class.R, R/RLum.Results-class.R, R/Risoe.BINfileData-class.R, R/Risoe.BINfileData2RLum.Analysis.R, R/analyse_IRSAR.RF.R, R/analyse_SAR.CWOSL.R, R/analyse_baSAR.R, R/analyse_pIRIRSequence.R, R/analyse_portableOSL.R, R/calc_FastRatio.R, R/calc_OSLLxTxDecomposed.R, R/calc_gSGC_feldspar.R, R/combine_De_Dr.R, R/fit_SurfaceExposure.R, R/internals_RLum.R, R/merge_RLum.Data.Curve.R, R/methods_DRAC.R, R/methods_RLum.R, R/plot_KDE.R, R/plot_ViolinPlot.R, R/read_BIN2R.R, R/verify_SingleGrainData.R, R/write_R2BIN.R, tests/testthat/test_RLum.Data.Spectrum.R, tests/testthat/test_Risoe.BINfileData2RLum.Analysis.R, tests/testthat/test_analyse_IRSAR.RF.R, tests/testthat/test_analyse_pIRIRSequence.R, tests/testthat/test_internals.R
This is just for convenience, especially for when we want to quote the items being collapsed.
=> Add the .collapse() helper function

tests/testthat/test_analyse_baSAR.R
This is part of #243 in preparation for #273.
=> Add a snapshot test for analyse_baSAR()

R/analyse_FadingMeasurement.R, R/fit_EmissionSpectra.R, tests/testthat/test_analyse_FadingMeasurement.R
These were caused by changes for #277.
=> Fix minor losses of coverage

R/analyse_baSAR.R, R/combine_De_Dr.R, R/internals_RLum.R, R/plot_AbanicoPlot.R, R/plot_FilterCombinations.R, R/plot_Histogram.R, R/plot_RLum.Data.Spectrum.R, R/read_TIFF2R.R, R/report_RLum.R, R/write_R2TIFF.R, tests/testthat/test_internals.R
=> Add the .require_suggested_package() helper function

R/plot_RLum.Analysis.R, tests/testthat/test_plot_RLum.Analysis.R
Various cleanups with additional tests for increased coverage.
=> Consolidate code and increase coverage in plot_RLum.Analysis()

R/fit_OSLLifeTimes.R, tests/testthat/test_fit_OSLLifeTimes.R
=> Fix crash in fit_OSLLifeTimes()

R/analyse_Al2O3C_ITC.R, R/analyse_Al2O3C_Measurement.R, R/analyse_IRSAR.RF.R, R/analyse_SAR.CWOSL.R, R/analyse_baSAR.R, R/analyse_pIRIRSequence.R, R/extract_IrradiationTimes.R, R/fit_EmissionSpectra.R, R/fit_OSLLifeTimes.R, R/internals_RLum.R, R/plot_DRCSummary.R, R/plot_RLum.R, R/read_BIN2R.R, R/write_RLum2CSV.R, tests/testthat/test_fit_OSLLifeTimes.R, tests/testthat/test_internals.R
This adds the very simple `.listify()` helper, with essentially the implementation as posted in the issue, with the only difference of using `inherits()` instead of `is()`. Fixes #299.
=> Add the .listify() internal helper function

R/plot_RLum.R, tests/testthat/test_plot_RLum.R
One extra use of `.validate_class()`.
=> Validate input data to plot_RLum()

R/plot_GrowthCurve.R, man/plot_GrowthCurve.Rd, tests/testthat/test_analyse_SAR.TL.R, tests/testthat/test_plot_GrowthCurve.R
This addresses points 2, 3 and partly 4 of #307, adds more input validation and restore some coverage lost when we restricted tests to R release, as coverage runs on 4.3.
=> Address some problems in plot_GrowthCurve()

tests/testthat/_snaps/calc_CosmicDoseRate.md, tests/testthat/test_calc_CosmicDoseRate.R
=> Add snapshot tests for calc_CosmicDoseRate()

R/calc_CosmicDoseRate.R, tests/testthat/test_calc_CosmicDoseRate.R
This uses `cut()` to find the index of the interval in which a value falls, rather than a series of `if/else` branches. This will improve our coverage in this file by a few lines.
=> Consolidate code in calc_CosmicDoseRate()

R/plot_GrowthCurve.R, tests/testthat/test_plot_GrowthCurve.R
=> Consolidate code for the EXP methods in plot_GrowthCurve()

R/plot_GrowthCurve.R, man/plot_GrowthCurve.Rd
This fixes the documentation problem and does some more code consolidation. Fixes #307.
=> more code consolidation in plot_GrowthCurve()

R/internals_RLum.R, R/read_BIN2R.R, R/read_XSYG2R.R, tests/testthat/test_read_XSYG2R.R
This allows a minor code simplification in a couple of places.
=> Add the verbose argument to .download_file()

R/extract_ROI.R, R/read_BIN2R.R, man/extract_ROI.Rd, man/read_BIN2R.Rd, tests/testthat/test_analyse_baSAR.R, tests/testthat/test_convert_SG2MG.R, tests/testthat/test_convert_XSYG2CSV.R, tests/testthat/test_read_BIN2R.R
Very small things I found while looking at this file.
=> Small cleanups in read_BIN2R()

R/read_BIN2R.R
=> Fix checks on field sizes in read_BIN2R()

NEWS.Rmd, R/analyse_pIRIRSequence.R, tests/testthat/test_analyse_pIRIRSequence.R
=> Fix warning message and restore coverage in analyse_pIRIRSequence()

R/read_BIN2R.R
By postponing the creation of the `Risoe.BINfileData` object at the end of `read_BIN2R()`, we can clean the metadata up operating on the data.table columns, thus avoiding extra copies and hard to read code.
This brings a tiny speed-up on the 46M file, perhaps 0.5s. Part of #298.
=> Use data.table operations before generating the output object

R/plot_DoseResponseCurve.R, tests/testthat/test_analyse_IRSAR.RF.R
=> Deals with NAs when computing densities in plot_DoseResponseCurve()

R/fit_DoseResponseCurve.R
This addresses the main points in #364.
=> Improve terminal feedback in fit_DoseResponseCurve()

tests/testthat/_snaps/calc_OSLLxTxDecomposed.md, tests/testthat/_snaps/calc_OSLLxTxRatio.md, tests/testthat/test_calc_OSLLxTxDecomposed.R, tests/testthat/test_calc_OSLLxTxRatio.R
=> Add snapshot tests for calc_OSLLxTxDecomposed() and calc_OSLLxTxRatio()

R/read_BIN2R.R
This adds an inner function to consolidates the code to read the strings.
Each string is now read up to its total allocated size with one single call to `readBin()`, while the call to `readChar()` is done on the raw vector up to the used size (or forced size for some time/date fields): this avoids calls to `seek.connection()` that were before necessary when we were only reading the used part of the field.
=> Streamline the reading of strings in read_BIN2R()

R/calc_OSLLxTxDecomposed.R, R/calc_OSLLxTxRatio.R, R/internals_RLum.R
=> Extract shared code to calculate the LxTx error to an internal helper

R/plot_RLum.Data.Spectrum.R
This should be a clear improvement on what we had before. Fixes #371.
=> Fix the colour ramps in plot_RLum.Data.Spectrum()

R/methods_DRAC.R, R/use_DRAC.R, tests/testthat/test_methods_DRAC.R
This adds a few new tests to cover most of the remaining corner cases.
=> Add more coverage to the DRAC functions

tests/testthat/_snaps/read_BIN2R.md, tests/testthat/test_read_BIN2R.R
=> Add snapshot tests for read_BIN2R()

R/methods_DRAC.R
=> Eliminate code in methods_DRAC.R that shouldn't be required anymore

NEWS.Rmd, R/analyse_IRSAR.RF.R, man/analyse_IRSAR.RF.Rd, tests/testthat/test_analyse_IRSAR.RF.R
=> Better validation of sequence_structure in analyse_IRSAR.RF()

R/analyse_FadingMeasurement.R
@RLumSK See if this fixes #390, as I don't know how to reproduce your problem.
=> Use bquote() inside expression() as 'expression' may show in the title

R/analyse_IRSAR.RF.R, tests/testthat/test_analyse_IRSAR.RF.R
This simplifies a bit the code, and with the added tests should add some more coverage in `analyse_IRSAR.RF()`.
=> Code cleanup and validation of RF_nat.lim and RF_reg.lim

R/analyse_IRSAR.RF.R, tests/testthat/test_analyse_IRSAR.RF.R
Fixes #401, as well as another corner case.
=> Add some extra checks after limitations to the curves are applied

R/analyse_IRSAR.RF.R, man/analyse_IRSAR.RF.Rd, tests/testthat/test_analyse_IRSAR.RF.R
This also clarifies a bit the docs.
=> Clean up some of the code in analyse_IRSAR.IR() and increase coverage

R/analyse_IRSAR.RF.R
=> Clarify code for the computation of algorithm_error in analyse_IRSAR.RF()

NEWS.Rmd, R/analyse_IRSAR.RF.R, R/analyse_baSAR.R, man/analyse_IRSAR.RF.Rd, tests/testthat/test_analyse_IRSAR.RF.R
=> Rename method.control to method_control in analyse_IRSAR.RF()

NEWS.Rmd, R/plot_RLum.Data.Spectrum.R, tests/testthat/test_plot_RLum.Data.Spectrum.R
This fixes all the crashing examples in #415.
=> Fix crashes in plot_RLum.Data.Spectrum() with bin.rows/bin.cols too high

R/plot_RLum.Data.Spectrum.R, tests/testthat/test_plot_RLum.Data.Spectrum.R
This covers some other corner cases in `plot_RLum.Data.Spectrum()` and closes #415.
=> Improve input validation in plot_RLum.Data.Spectrum()

R/analyse_Al2O3C_Measurement.R, tests/testthat/test_analyse_Al2O3C_Measurement.R
=> Don't compute a confidence interval when only one observation is available

R/calc_IEU.R, tests/testthat/test_calc_IEU.R
This removes the unnecessary for loop mentioned in https://github.com/R-Lum/Luminescence/issues/429#issuecomment-2480692347 but keeps the suspicious rounding. It then adds some extra validation and tests. Part of #429.
=> Remove unnecessary loops in calc_IEU() and improve validation

R/calc_IEU.R
This removes the massive code repetition by creating two inner functions that are called multiple times:
- main.calculation() to perform the core algorithm
- do.plot() to plot the results
This is also faster than before: running all tests used to take over 3s, now it takes just 1s.
Fixes #429.
=> Consolidate code in calc_IEU()

R/merge_RLum.Data.Spectrum.R, man/merge_RLum.Data.Spectrum.Rd, tests/testthat/test_merge_RLum.Data.Spectrum.R
=> Add option to control the largest acceptable temperature difference

R/Risoe.BINfileData-class.R, R/calc_FadingCorr.R, R/read_BIN2R.R, man/calc_FadingCorr.Rd, tests/testthat/test_RisoeBINfileData-class.R, tests/testthat/test_calc_FadingCorr.R, tests/testthat/test_read_BIN2R.R
=> Improve input validation for a logical input

NEWS.Rmd, R/write_R2BIN.R, man/write_R2BIN.Rd, tests/testthat/test_write_R2BIN.R
=> Add the verbose option to write_R2BIN()

NEWS.Rmd, R/extract_IrradiationTimes.R, tests/testthat/test_extract_IrradiationTimes.R
=> Fix subset expression in extract_IrradiationTimes()

R/import_Data.R, man/import_Data.Rd
=> Generate automatically the list of functions supported by import_Data()

R/plot_KDE.R, tests/testthat/test_plot_KDE.R
This introduces a small inner function to consolidate some very repetitive code.
=> Consolidate code and increase coverage in plot_KDE()

R/fit_LMCurve.R, tests/testthat/test_fit_LMCurve.R
Adds a couple of new tests and some trivial code cleanup.
=> Complete coverage for fit_LMCurve.R

R/analyse_IRSAR.RF.R, R/analyse_SAR.CWOSL.R, R/analyse_pIRIRSequence.R, R/analyse_portableOSL.R, R/calc_AverageDose.R, R/calc_CentralDose.R, R/calc_Huntley2006.R, R/calc_MinDose.R, R/calc_OSLLxTxRatio.R, R/convert_RLum2Risoe.BINfileData.R, R/extract_IrradiationTimes.R, R/fit_DoseResponseCurve.R, R/fit_OSLLifeTimes.R, R/fit_SurfaceExposure.R, R/fit_ThermalQuenching.R, R/methods_DRAC.R, R/plot_DRCSummary.R, R/plot_RLum.Results.R, R/verify_SingleGrainData.R
This is described as being marginally faster and it's also shorter.
=> Replace uses of any(is.na(x)) with anyNA(x)

R/fit_OSLLifeTimes.R, tests/testthat/test_fit_OSLLifeTimes.R
Adds some tests to increase coverage.
=> Increase coverage in fit_OSLLifeTimes.R

R/analyse_pIRIRSequence.R, R/merge_RLum.Results.R, R/read_RF2R.R, tests/testthat/test_analyse_pIRIRSequence.R, tests/testthat/test_merge_RLum.Results.R, tests/testthat/test_read_RF2R.R, tests/testthat/test_write_RLum2CSV.R
=> Improve input validation against a list with an empty RLum.Results object

R/Analyse_SAR.OSLdata.R, R/analyse_pIRIRSequence.R, R/calc_CosmicDoseRate.R, R/calc_FiniteMixture.R, R/calc_Huntley2006.R, R/calc_MinDose.R, R/report_RLum.R, man/calc_MinDose.Rd, tests/testthat/test_calc_Huntley2006.R
This adds coverage for these files:
- Analyse_SAR.OSLdata.R
- analyse_pIRIRSequence.R
- calc_CosmicDoseRate.R
- calc_Huntley2006.R
- report_RLum.R
=> More coverage and code consolidation

R/fit_DoseResponseCurve.R
=> Fix bounds in fit_DoseResponseCurve()

NEWS.Rmd, R/plot_DRTResults.R, tests/testthat/test_plot_DRTResults.R
=> Fix crash in plot_DRTResults() due to wrong subsetting

R/PSL2Risoe.BINfileData.R, R/RLum.Analysis-class.R, R/analyse_Al2O3C_CrossTalk.R, R/analyse_IRSAR.RF.R, R/analyse_portableOSL.R, R/convert_RLum2Risoe.BINfileData.R, R/fit_OSLLifeTimes.R, R/merge_RLum.Analysis.R, R/plot_DetPlot.R, R/plot_RLum.Analysis.R, R/plot_RLum.R, R/write_RLum2CSV.R, tests/testthat/test_PSL2RisoeBINfiledata.R, tests/testthat/test_analyse_Al2O3C_CrossTalk.R, tests/testthat/test_analyse_IRSAR.RF.R, tests/testthat/test_analyse_portableOSL.R, tests/testthat/test_convert_RLum2Risoe.BINfileData.R, tests/testthat/test_fit_OSLLifeTimes.R, tests/testthat/test_merge_RLum.Analysis.R, tests/testthat/test_names_RLum.R, tests/testthat/test_plot_DetPlot.R, tests/testthat/test_plot_RLum.Analysis.R, tests/testthat/test_plot_RLum.R, tests/testthat/test_structure_RLum.R, tests/testthat/test_write_RLum2CSV.R
=> Improve input validation against an empty RLum.Analysis object

NEWS.Rmd, R/calc_gSGC.R, tests/testthat/test_calc_gSGC.R
=> Ensure errors are non-negative in calc_gSGC()

R/analyse_Al2O3C_Measurement.R, tests/testthat/test_analyse_Al2O3C_Measurement.R
=> Fix how test_parameters is listified in analyse_Al2O3C_Measurement()

R/RLum.Data-class.R, R/RLum.Data.Image-class.R, R/plot_RLum.Data.Image.R, R/trim_RLum.Data.R, R/write_R2TIFF.R, tests/testthat/test_RLum.Data.Image.R, tests/testthat/test_merge_RLum.Analysis.R, tests/testthat/test_plot_RLum.Data.Image.R, tests/testthat/test_plot_RLum.R, tests/testthat/test_trim_RLum.Data.R, tests/testthat/test_view.R, tests/testthat/test_write_R2TIFF.R
=> Improve input validation against an empty RLum.Data.Image object

R/Risoe.BINfileData2RLum.Analysis.R, R/analyse_FadingMeasurement.R, R/analyse_SAR.TL.R, tests/testthat/test_analyse_FadingMeasurement.R, tests/testthat/test_analyse_SAR.TL.R
Adds coverage for these files:
- analyse_FadingMeasurement.R
- analyse_SAR.TL.R
- Risoe.BINfileData2RLum.Analysis.R
=> A bit more coverage

R/fit_CWCurve.R, R/fit_LMCurve.R, tests/testthat/test_fit_CWCurve.R, tests/testthat/test_fit_LMCurve.R
=> Improve input validation against an empty RLum.Data.Curve object

R/fit_DoseResponseCurve.R
This removes some code duplication for the QDR, LIN and EXP methods. Part of #141.
=> Code consolidation in fit_DoseResponseCurve()

R/calc_FastRatio.R, R/convert_Wavelength2Energy.R, R/fit_EmissionSpectra.R, R/fit_OSLLifeTimes.R, R/fit_SurfaceExposure.R, tests/testthat/test_calc_FastRatio.R, tests/testthat/test_convert_Wavelength2Energy.R, tests/testthat/test_fit_EmissionSpectra.R, tests/testthat/test_fit_OSLLifeTimes.R, tests/testthat/test_fit_SurfaceExposure.R
=> Improve validation against an empty matrix

NEWS.Rmd, NEWS.md, R/analyse_SAR.CWOSL.R, tests/testthat/test_analyse_SAR.CWOSL.R
=> Fix shifting of the curve away from zero in analyse_SAR.CWOSL()

NEWS.Rmd, NEWS.md, R/RLum.Analysis-class.R, R/RLum.Data-class.R, R/Risoe.BINfileData-class.R, man/RLum.Analysis-class.Rd, man/RLum.Data-class.Rd, man/Risoe.BINfileData-class.Rd, tests/testthat/test_metadata.R
=> Add functionality to remove metadata using replace_metadata()

R/calc_Huntley2006.R
This consolidates some code related to `GC.settings` and fixes #543.
=> Restore the dose response curve plots in calc_Huntley2006()

R/fit_IsothermalHolding.R, man/fit_IsothermalHolding.Rd
=> Produce a data frame with the fitted parameters from fit_IsothermalHolding()

R/fit_IsothermalHolding.R, tests/testthat/test_fit_IsothermalHolding.R
=> Fix warnings from fit_IsothermalHolding() when processing multiple samples

NEWS.Rmd, NEWS.md, R/fit_CWCurve.R, R/fit_LMCurve.R, tests/testthat/test_fit_CWCurve.R, tests/testthat/test_fit_LMCurve.R
=> Make fit_LMCurve() and fit_CWCurve() more resilient to plot failures

NEWS.Rmd, NEWS.md, R/analyse_pIRIRSequence.R, tests/testthat/test_analyse_pIRIRSequence.R
=> Ensure that sequence.structure contains at least one IR step

tests/testthat/_snaps/calc_CosmicDoseRate.md, tests/testthat/test_calc_CosmicDoseRate.R
This adds two new snapshot tests to bring coverage to 100% for this file.
=> Complete coverage for calc_CosmicDoseRate.R

R/analyse_Al2O3C_CrossTalk.R, R/internals_Thermochronometry.R, R/methods_RLum.R, R/read_BIN2R.R, R/write_R2BIN.R
=> Replace sapply(x, length) and similar with lengths()

R/calc_OSLLxTxRatio.R
These make the code slightly more readable and compact.
=> Consolidate code in calc_OSLLxTxRatio()

R/calc_CentralDose.R, man/calc_CentralDose.Rd, tests/testthat/_snaps/calc_CentralDose.md, tests/testthat/test_calc_CentralDose.R
In particular this improves the handling of the `sigmab` argument.
=> Consolidate code in calc_CentralDose() and complete coverage

R/RLum.Analysis-class.R, tests/testthat/test_RLum.Analysis-class.R
This improves a corner case validation and removes the unreachable `tryCatch()` error block. Fixes #629.
=> Remove unreachable error block in sort_RLum()

NEWS.Rmd, R/RLum.Analysis-class.R, tests/testthat/test_RLum.Analysis-class.R
+ ho housing keeping of code structure
+ ch store lists instead of long characters
+ up tests
+ ad NEWS
=> structure_RLum():

NEWS.Rmd, NEWS.md, R/plot_KDE.R, man/plot_KDE.Rd, tests/testthat/test_plot_KDE.R
=> Improve input validation in plot_KDE()

R/plot_AbanicoPlot.R, R/plot_DRTResults.R, R/plot_Histogram.R, R/plot_KDE.R, R/plot_RadialPlot.R, R/plot_ViolinPlot.R, man/plot_AbanicoPlot.Rd, man/plot_DRTResults.Rd, man/plot_Histogram.Rd, man/plot_KDE.Rd, man/plot_RadialPlot.Rd, man/plot_ViolinPlot.Rd, tests/testthat/test_plot_AbanicoPlot.R, tests/testthat/test_plot_DRTResults.R, tests/testthat/test_plot_Histogram.R, tests/testthat/test_plot_KDE.R, tests/testthat/test_plot_RadialPlot.R, tests/testthat/test_plot_ViolinPlot.R
This also sets some default values for arguments, rather than leaving then missing and setting them to a default value in the function body.
=> Improve validation of summary and summary.pos arguments

R/plot_AbanicoPlot.R, R/plot_Histogram.R, R/plot_KDE.R, R/plot_RadialPlot.R, tests/testthat/_snaps/plot_AbanicoPlot/abanico-expected.svg
This consolidates code in these functions:
- plot_AbanicoPlot()
- plot_Histogram()
- plot_KDE()
- plot_RadialPlot()
The change in the graphical snapshot for `plot_AbanicoPlot()` is only due to the fact that previously the label was
>       "n = 62 | in 2 sigma = 41.9 % "
and now is
>      "n = 62 | in 2 sigma = 41.9 %"
=> Code consolidation in generation of statistical summaries

R/fit_IsothermalHolding.R, tests/testthat/test_fit_IsothermalHolding.R
This fixes a crash on an example reported by @SalOehl.
Also this improves the progress report when fitting the BTS model with default values, as otherwise the progress bar gets stuck at 0% for very long.
=> Fix crash in fit_IsothermalHolding() if the GOK model doesn't fit

.github/workflows/R-CMD-check.yml
=> Reduce the number of machines running the CI actions

NEWS.Rmd, NEWS.md, R/analyse_portableOSL.R, tests/testthat/test_analyse_portableOSL.R
Fixes #675 alongside some small cleanups in the tests.
=> Don't lose dimensions when subsetting data in analyse_portableOSL()

NEWS.Rmd, NEWS.md, R/analyse_portableOSL.R, tests/testthat/test_analyse_portableOSL.R
=> Check the signal.integral argument only once in analyse_portableOSL()

NEWS.Rmd, NEWS.md, R/analyse_portableOSL.R, tests/testthat/test_analyse_portableOSL.R
=> Improve validation of signal.integral in analyse_portableOSL()

NEWS.Rmd, NEWS.md, R/analyse_portableOSL.R, man/analyse_portableOSL.Rd
=> Allow controlling cex and type in analyse_portableOSL()

NEWS.Rmd, NEWS.md, R/calc_FiniteMixture.R, tests/testthat/test_calc_FiniteMixture.R
Fixes #691 and cleans up some code.
=> Support non-consecutive values for n.components in calc_FiniteMixture()

NEWS.Rmd, NEWS.md, R/plot_KDE.R, man/plot_KDE.Rd
Fixes #700 alongside some other code cleanup.
=> Remove the output argument from plot_KDE()

NEWS.Rmd, NEWS.md, R/calc_FiniteMixture.R, tests/testthat/test_calc_FiniteMixture.R
=> Ensure that max.dose and min.dose are always computed

NEWS.Rmd, NEWS.md, R/calc_FiniteMixture.R
=> Remove blank gaps to the sides of the barplot in calc_FiniteMixture()

R/fit_DoseResponseCurve.R, tests/testthat/test_RLum.Analysis-class.R, tests/testthat/test_fit_DoseResponseCurve.R
=> Avoid mangling the function name with .replace_coef() in fit_DoseResponseCurve()

NEWS.Rmd, NEWS.md, R/calc_Huntley2006.R, tests/testthat/test_calc_Huntley2006.R
=> Amend error message if we've used the argument it would have suggested

R/calc_Huntley2006.R, tests/testthat/test_calc_Huntley2006.R
=> Validate n.MC and silently ensure that it's at least 2 in calc_Huntley2006()

NEWS.Rmd, NEWS.md, R/calc_Huntley2006.R, man/calc_Huntley2006.Rd, tests/testthat/test_calc_Huntley2006.R
=> Allow controlling cex in calc_Huntley2006()

NEWS.Rmd, NEWS.md, R/plot_Histogram.R
=> Fix the cex setting in the summary of plot_Histogram()

NEWS.Rmd, NEWS.md, R/fit_LMCurve.R, tests/testthat/test_fit_LMCurve.R, tests/testthat/test_plot_AbanicoPlot.R
=> Remove missing from values.bg in fit_LMCurve()

R/plot_DRTResults.R, man/plot_DRTResults.Rd
=> Fix cex setting in the summary/legend text of plot_DRTResults()

NEWS.Rmd, NEWS.md, R/plot_DRTResults.R
=> Improve the way in which colours and symbols are assigned to points

NEWS.Rmd, NEWS.md, R/fit_LMCurve.R, man/fit_LMCurve.Rd, tests/testthat/test_fit_LMCurve.R
=> Add support for bg.subtraction = "none" to fit_LMCurve()

NEWS.Rmd, NEWS.md, R/analyse_IRSAR.RF.R, man/analyse_IRSAR.RF.Rd
=> Add support for the verbose argument via ... to analyse_IRSAR.RF()

R/fit_LMCurve.R
This is required for https://github.com/tzerk/RLumShiny/issues/52.
=> Don't open the plot device unless plot = TRUE

R/analyse_IRSAR.RF.R, R/calc_CobbleDoseRate.R, R/calc_FuchsLang2001.R, R/calc_OSLLxTxDecomposed.R, R/fit_OSLLifeTimes.R, R/plot_RadialPlot.R, man/calc_CobbleDoseRate.Rd, tests/testthat/test_analyse_IRSAR.RF.R, tests/testthat/test_calc_CobbleDoseRate.R, tests/testthat/test_calc_FuchsLang2001.R, tests/testthat/test_calc_OSLLxTxDecomposed.R, tests/testthat/test_fit_OSLLifeTimes.R, tests/testthat/test_plot_RadialPlot.R
=> Improve validation against data.frames containing zeros

NEWS.Rmd, NEWS.md, R/analyse_IRSAR.RF.R, tests/testthat/test_analyse_IRSAR.RF.R
=> Don't attempt to show the density plot if n.MC = NULL

NEWS.Rmd, NEWS.md, R/plot_AbanicoPlot.R, tests/testthat/_snaps/plot_AbanicoPlot/default.svg, tests/testthat/_snaps/plot_AbanicoPlot/dispersion-error-bars.svg, tests/testthat/_snaps/plot_AbanicoPlot/dots-cex.svg, tests/testthat/_snaps/plot_AbanicoPlot/rotated.svg, tests/testthat/test_plot_AbanicoPlot.R
=> Respect the cex in plot_AbanicoPlot()

NEWS.Rmd, NEWS.md, R/RLum.Analysis-class.R
=> Vectorize translation to regular expression in get_RLum()

R/calc_FuchsLang2001.R, R/calc_HomogeneityTest.R, R/calc_MinDose.R, R/convert_CW2pHMi.R, R/convert_CW2pLM.R, R/convert_CW2pLMi.R, R/convert_CW2pPMi.R, R/fit_CWCurve.R, R/fit_DoseResponseCurve.R, R/fit_LMCurve.R, R/plot_DRTResults.R, tests/testthat/test_calc_FuchsLang2001.R, tests/testthat/test_calc_HomogeneityTest.R, tests/testthat/test_calc_MinDose.R, tests/testthat/test_convert_CW2pX.R, tests/testthat/test_fit_CWCurve.R, tests/testthat/test_fit_DoseResponseCurve.R, tests/testthat/test_fit_LMCurve.R, tests/testthat/test_plot_DRTResults.R
=> Improve validation against a single-column data frame

R/fit_IsothermalHolding.R, tests/testthat/test_fit_IsothermalHolding.R
This provides some feedback in the terminal in terms of median (IQR) of the two main parameters of the model `Et` and `log10(s)`. Those values are also returned in the `RLum.Results` object.
Part of #852.
=> Summarize the parameters of interest in fit_IsothermalHolding()

R/analyse_IRSAR.RF.R, R/plot_FilterCombinations.R, tests/testthat/test_analyse_IRSAR.RF.R, tests/testthat/test_plot_FilterCombinations.R
=> Improve validation against a list of 1-column data frames

R/calc_WodaFuchs2008.R, R/plot_Histogram.R, R/plot_ViolinPlot.R, tests/testthat/test_calc_WodaFuchs2008.R, tests/testthat/test_plot_Histogram.R, tests/testthat/test_plot_ViolinPlot.R
=> Improve validation against a data.frame with only a character column

NEWS.Rmd, NEWS.md, R/calc_MinDose.R, tests/testthat/test_calc_MinDose.R
=> Fix crash by ensuring that bs.M is at least 2 in calc_MinDose()

R/convert_CW2pHMi.R, R/convert_CW2pLMi.R, R/convert_CW2pPMi.R, R/fit_CWCurve.R, tests/testthat/test_convert_CW2pX.R, tests/testthat/test_fit_CWCurve.R
=> Improve validation against data frames with an NA column

R/calc_WodaFuchs2008.R, R/plot_OSLAgeSummary.R, R/zzz.R, man/plot_OSLAgeSummary.Rd, tests/testthat/test_calc_WodaFuchs2008.R, tests/testthat/test_plot_OSLAgeSummary.R, tests/testthat/test_zzz.R
=> Improve validation against a numeric vector with NaN

R/calc_OSLLxTxRatio.R, tests/testthat/test_calc_OSLLxTxRatio.R
=> Improve validation against an empty numeric vector

NEWS.Rmd, NEWS.md, R/calc_MinDose.R, tests/testthat/test_calc_MinDose.R
=> Check that after removal of NAs there is still data in calc_MinDose()

NEWS.Rmd, NEWS.md, R/analyse_Al2O3C_Measurement.R, tests/testthat/test_analyse_Al2O3C_Measurement.R
Fixes #930 and cleans up some of the code.
=> Fix validation of cross_talk_correction in analyse_Al2O3C_Measurement()

R/RLum.Analysis-class.R, R/analyse_Al2O3C_ITC.R, R/analyse_Al2O3C_Measurement.R, R/remove_SignalBackground.R, tests/testthat/test_analyse_Al2O3C_ITC.R, tests/testthat/test_analyse_Al2O3C_Measurement.R, tests/testthat/test_remove_SignalBackground.R, tests/testthat/test_view.R
=> Improve validation against an empty RLum.Analysis object

NEWS.Rmd, NEWS.md, R/fit_DoseResponseCurve.R, tests/testthat/test_fit_DoseResponseCurve.R
=> Report correctly the fit outcome for QDR in fit_DoseResponseCurve()

NEWS.Rmd, NEWS.md, R/analyse_SAR.CWOSL.R, R/fit_DoseResponseCurve.R, R/plot_DoseResponseCurve.R, man/fit_DoseResponseCurve.Rd, tests/testthat/_snaps/analyse_SAR.CWOSL.md, tests/testthat/_snaps/fit_DoseResponseCurve.md
=> Reorder and rename fields in object returned by fit_DoseResponseCurve()

R/fit_IsothermalHolding.R, tests/testthat/test_fit_IsothermalHolding.R
=> Fix crash in fit_IsothermalHolding() if no BTS model fits

NEWS.Rmd, NEWS.md, R/plot_RLum.Data.Spectrum.R, man/plot_RLum.Data.Spectrum.Rd, tests/testthat/test_plot_RLum.Data.Spectrum.R
=> Check that ylim doesn't remove all channels in plot_RLum.Data.Spectrum()

NEWS.Rmd, NEWS.md, R/plot_RLum.Data.Image.R, man/plot_RLum.Data.Image.Rd, tests/testthat/_snaps/plot_RLum.Analysis/image.svg, tests/testthat/_snaps/plot_RLum.Data.Image/contour.svg, tests/testthat/_snaps/plot_RLum.Data.Image/raster-lin-stretch.svg, tests/testthat/test_plot_RLum.Data.Image.R
=> Add support for mtext in plot_RLum.Data.Image()

NEWS.Rmd, NEWS.md, R/plot_AbanicoPlot.R, tests/testthat/test_plot_AbanicoPlot.R
This also adds validation for other arguments.
Fixes #1036.
=> Fix crash in plot_AbanicoPlot() when frame = NULL

NEWS.Rmd, NEWS.md, R/combine_De_Dr.R, man/combine_De_Dr.Rd, tests/testthat/test_combine_De_Dr.R
=> Allow to set the random seed for JAGS in combine_De_Dr()

NEWS.Rmd, NEWS.md, R/calc_EED_Model.R, tests/testthat/test_calc_EED_Model.R
=> Prettify error message reported by calc_EED_Model()

NEWS.Rmd, NEWS.md, R/fit_CWCurve.R, man/fit_CWCurve.Rd, tests/testthat/_snaps/fit_CWCurve.md
=> Report only as many components as fitted from fit_CWCurve()
