R-Lum/Luminescence

- R/Risoe.BINfileData2RLum.Analysis.R
- man/Risoe.BINfileData2RLum.Analysis.Rd
Depending on the query the function returns empty RLum.Analysis objects, i.e. the object has 0 records. Further processing of these objects then often require manually removing the empty objects first. We can skip this not so easy task by dropping all empty objects already here.
Example:
```r
library(Luminescence)
data("ExampleData.BINfileData")
bin <- CWOSL.SAR.Data
print(Risoe.BINfileData2RLum.Analysis(bin, ltype = "IRSL", set = 2, keep.empty = TRUE))
print(Risoe.BINfileData2RLum.Analysis(bin, ltype = "IRSL", set = 2, keep.empty = FALSE))
```
> Bin2RLum: new argument 'keep.empty' to discard 0-record object

- R/convert_Wavelength2Energy.R
- tests/testthat/test_convert_Wavelength2Energy.R
> Don't let a 1-column matrix become a vector in convert_Wavelength2Energy()

- R/calc_Lamothe2003.R
- tests/testthat/test_calc_Lamothe2003.R
This introduces checks similar to those that were already present for `dose_rate.envir` and `dose_rate.source`. Fixes #131.
This also fixes some tests that were not actually checking correctly for errors due to wrong nesting of `suppressWarning()`, whose closing bracket was misplaced.
> Check length of g_value argument in calc_Lamothe2003().

- R/calc_TLLxTxRatio.R
- tests/testthat/test_calc_TLLxTxRatio.R
This gives a default value to the `BG.Error` variable, as otherwise it wouldn't have any in the `Tx.data.background=NULL` case. Fixes #129.
The additional test added also brings coverage to 100% (#121).
> Fix crash in calc_TLLxTxRatio() if Tx.data.background=NULL.

- tests/testthat/test_read_RF2R.R
This adds tests to bring coverage for `read_RF2R.R` to 100% (#121).
> Complete coverage for read_RF2R.R.

- tests/testthat/test_calc_gSGC_feldspar.R
This brings coverage for this file from 98.33% to 98.89%. Part of #121.
> Increase coverage in calc_gSGC_feldspar.R.

- tests/testthat/test_calc_Statistics.R
This adds a test for error-free data sets passed to `calc_Statistics()` and brings coverage for `calc_Statistics.R` to 100% (#121).
> complete coverage in calc_Statistics.R

- R/calc_Statistics.R
- tests/testthat/test_calc_Statistics.R
When `n.MCM` is not NULL, `data.MCM` is a matrix with as many columns as number of Monte Carlo samples: calling `sum()` over it when computating skewness and kurtosis will sum `n * n.MCM` values, so we must divide by `n * n.MCM` to produce the correct expectations.
Fixes #122.
> Fix computation of skewness and kurtosis with MCM.

- R/calc_FiniteMixture.R
- tests/testthat/test_calc_FiniteMixture.R
Various cleanups found while I was looking at this function:
* simplified and streamlined a bit the logic for input validation
* changed the occurrences of `cat(paste("error message")); stop(domain = NA)` to `stop("error message", call. = FALSE)`, which makes it easier to test and is what is more commonly used
* adjusted a bit the error messages
* expanded tests on inputs
> Clean up input validation in calc_FiniteMixture()

- tests/testthat/test_write_RLum2CSV.R
This works locally, it should be fine also on CI. Fixes #148.
> Don't pollute the working directory with generated output from test_write_RLum2CSV.R

- R/addins_RLum.R
- R/analyse_baSAR.R
- R/combine_De_Dr.R
- R/install_DevelopmentVersion.R
- R/plot_AbanicoPlot.R
- R/plot_FilterCombinations.R
- R/plot_Histogram.R
- R/plot_RLum.Data.Spectrum.R
- R/read_TIFF2R.R
- R/report_RLum.R
- R/write_R2TIFF.R
Testing blocks that depend on the result of `requireNamespace()` is almost impossible, as the packages being checked are by design present on CI and in our development machines. This marks those regions with `nocov start` and `nocov end` to tell `covr` that they shouldn't be counted as missing from coverage. Helps marginally with #121.
> Use nocov start/end to exclude untestable regions from coverage

- R/internals_RLum.R
- tests/testthat/test_internals.R
There are two problems with the current implementation of `.throw_error()` and `.throw_warning()` which were noted in #152:
```R
> .validate_positive_scalar(iris)
Error: [.validate_positive_scalar()] 'iris' must be a positive scalar[iris()] 'iris' must be a positive scalar
```
1. The name of the caller function is not computed correctly if the caller has arguments, which messes up the output
2. If the caller is an internal function, the internal name would be exposed to the user, rather than the name of the function the user called
This PR makes the function print the name of the calling function just once and allows using them from other internal functions, thanks to the new `nframe` argument that allows to control which function name is reported from the error/warning message.
When …
> Fix .throw_error() and .throw_warning()

- NEWS.Rmd
- R/fit_EmissionSpectra.R
- tests/testthat/test_fit_EmissionSpectra.R
Argument `input_scale` was not propagated in the self-call, so it was effectively ignored in most cases.
> Propagate the input_scale argument in fit_EmissionSpectra()

- NEWS.Rmd
- R/fit_SurfaceExposure.R
- tests/testthat/test_fit_SurfaceExposure.R
Fixes a dimension mismatch in `fit_SurfaceExposure()` when the input data contains `NA`s, by removing them before subsetting the data further. Fixes #162.
> Remove warnings from fit_SurfaceExposure() if data contains NAs

- NEWS.Rmd
- R/fit_SurfaceExposure.R
- tests/testthat/test_fit_SurfaceExposure.R
Fixes these two little bugs:
1. A small bug in data subsetting, similar to #162 
2. An error reported if called on an `RLum.Results` object due to an assignment to a wrongly-named variable
> two small errors in fit_SurfaceExposure()

- tests/testthat/test_analyse_SAR.CWOSL.R
- tests/testthat/test_analyse_pIRIRSequence.R
- tests/testthat/test_calc_AliquotSize.R
- tests/testthat/test_calc_Huntley2006.R
- tests/testthat/test_plot_GrowthCurve.R
We don't support R versions < 4.3, so the test for results previous to the RNG changes of R 3.6 can be removed.
> Remove test results for R version < 3.6

- R/calc_gSGC_feldspar.R
- R/read_RF2R.R
- tests/testthat/setup.R
- tests/testthat/test_Analyse_SAROSLdata.R
- tests/testthat/test_Risoe.BINfileData2RLum.Analysis.R
- tests/testthat/test_analyse_Al2O3C_ITC.R
- tests/testthat/test_analyse_Al2O3C_Measurement.R
- tests/testthat/test_analyse_IRSAR.RF.R
- tests/testthat/test_calc_FiniteMixture.R
- tests/testthat/test_calc_Lamothe2003.R
- tests/testthat/test_calc_MinDose.R
- tests/testthat/test_calc_gSGC_feldspar.R
- tests/testthat/test_combine_De_Dr.R
- tests/testthat/test_convert_XSYG2CSV.R
- tests/testthat/test_extract_IrradiationTimes.R
- tests/testthat/test_fit_EmissionSpectra.R
- tests/testthat/test_fit_LMCurve.R
- tests/testthat/test_read_Daybreak2R.R
- tests/testthat/test_read_RF2R.R
- tests/testthat/test_template_DRAC.R
- tests/testthat/test_use_DRAC.R
This introduces the `SW()` function to silence pretty much everything that the functions write to the terminal during the tests, and starts applying it to a first bunch of tests. Part of #120.
> Start silencing output from tests

- R/analyse_SAR.TL.R
- R/internals_RLum.R
- R/plot_GrowthCurve.R
- R/write_R2BIN.R
- R/write_RLum2CSV.R
- tests/testthat/setup.R
- tests/testthat/test_analyse_Al2O3C_CrossTalk.R
- tests/testthat/test_analyse_SAR.CWOSL.R
- tests/testthat/test_analyse_SAR.TL.R
- tests/testthat/test_analyse_pIRIRSequence.R
- tests/testthat/test_calc_AverageDose.R
- tests/testthat/test_calc_CommonDose.R
- tests/testthat/test_calc_CosmicDoseRate.R
- tests/testthat/test_calc_FadingCorr.R
- tests/testthat/test_calc_FastRatio.R
- tests/testthat/test_calc_FuchsLang2001.R
- tests/testthat/test_calc_HomogeneityTest.R
- tests/testthat/test_calc_Huntley2006.R
- tests/testthat/test_convert_Daybreak2CSV.R
- tests/testthat/test_fit_SurfaceExposure.R
- tests/testthat/test_internals.R
- tests/testthat/test_merge_Risoe.BINfileData.R
- tests/testthat/test_plot_GrowthCurve.R
- tests/testthat/test_write_R2BIN.R
- tests/testthat/test_write_RLum2CSV.R
This moves the `SW()` function into `R/internals_RLum.R`, as having it defined in `tests/testthat/setup.R` doesn't work for `covr::file_coverage()`, which doesn't source that file automatically (as opposed to what happens with `testthat::test_file()` and `covr::package_coverage()`), and that makes it harder to work iteratively with it.
This also completes the silencing of the test files I've touched until now for coverage (part of #120).
> Silence some more test output

- NEWS.Rmd
- R/plot_NRt.R
- tests/testthat/test_plot_NRt.R
Fixes two crashes in `plot_NRt()` and adds a test for the wrong `if` statement (the code was already corrected in 542522e). Closes #177.
> fixes for crashes in plot_NRt()

- tests/testthat/test_RLum.Analysis-class.R
- tests/testthat/test_calc_FastRatio.R
- tests/testthat/test_report_RLum.R
- tests/testthat/test_subset_RLum.R
Calling `data(datasetName)` without the `envir = environment()` option loads the objects in the workspace, and tests shouldn't do that.
> Don't pollute the workspace with example data when running tests

- R/plot_KDE.R
- tests/testthat/test_plot_KDE.R
This makes the check for `Inf` values a bit easier to follow and now it reports the correct row indices removed. Fixes #187.
> Simplify and correct the check for Inf in plot_KDE()

- NEWS.Rmd
- R/fit_OSLLifeTimes.R
- man/fit_OSLLifeTimes.Rd
- tests/testthat/test_fit_OSLLifeTimes.R
This now takes `signal.range` into account and establishes the minimum required also accounting for `n.components`. Fixes #182.
> Improve validation of data size in fit_OSLLifeTimes()

- NEWS.Rmd
- R/calc_WodaFuchs2008.R
- man/calc_WodaFuchs2008.Rd
- tests/testthat/test_calc_WodaFuchs2008.R
This is another case (like #189) where the code accepted more types than documented, but dealt with it incorrectly. Now what we accept is fully documented, and the code is tested.
This also fixes the check for NAs: the previous code did `sum(is.na(data[,2]) == nrow(data))`, but what was meant was `sum(is.na(data[,2])) == nrow(data)`. I ended up rewriting it in an even cleaner way.
> Support vectors and single-colums dataframes in calc_WodaFuchs2008()

- R/plot_DetPlot.R
- man/plot_DetPlot.Rd
- tests/testthat/test_plot_DetPlot.R
By enforcing that `signal.integral.max > signal.integral.min` we also avoid that the computation of the number of channels produces ` Inf` (fixes #203).
Locally, running coverage on this produces this error from the test that uses `multicore = 1`:
```console
Error in `checkForRemoteErrors(val)`: one node produced an error:
could not find function ".validate_positive_scalar"
```
That error would go away if I used `Luminescence:::.validate_positive_scalar`, but that seems to be against the CRAN policy. Alternatively, one could move the validation checks before the self-call.
But in the meantime, let's see if CI is happy with it as it is.
> Validate signal and background integral values in plot_DetPlot()

- R/analyse_Al2O3C_ITC.R
- R/analyse_baSAR.R
- R/calc_MinDose.R
- R/fit_LMCurve.R
- tests/testthat/test_analyse_Al2O3C_ITC.R
- tests/testthat/test_plot_AbanicoPlot.R
- tests/testthat/test_plot_Functions.R
- tests/testthat/test_read_BIN2R.R
- tests/testthat/test_read_SPE2R.R
This silences the last few test outputs, especially those from `read_SPE2R()` which required a special treatment. Now the test output is totally clean! Fixes #120.
> Finish silencing the test ouput

- NEWS.Rmd
- R/fit_CWCurve.R
- man/fit_CWCurve.Rd
- tests/testthat/test_fit_CWCurve.R
> Remove the output.path argument from fit_CWCurve()

- NEWS.Rmd
- R/analyse_SAR.CWOSL.R
- R/analyse_pIRIRSequence.R
- R/plot_DetPlot.R
- tests/testthat/test_plot_DetPlot.R
This now checks that we have enough valid results from the calls to `analyse_pIRIRSequence()` before continuing. Fixes #210.
> Fix crash in plot_DetPlot(..., analyse_function = "analyse_pIRIRSequence")

- NEWS.Rmd
- R/plot_GrowthCurve.R
- man/plot_GrowthCurve.Rd
- tests/testthat/test_plot_GrowthCurve.R
> Remove the defunct na.rm option from plot_GrowthCurve()

- NEWS.Rmd
- R/calc_WodaFuchs2008.R
- tests/testthat/test_calc_WodaFuchs2008.R
A quick and dirty fix for the example posted in #199.
I ended up with the `tryCatch()` solution because in the tests we have already an example in which the `data` slot is present but it's not the first entry:
```R
obj <- calc_CommonDose(ExampleData.DeValues$BT998, verbose = FALSE)
expect_silent(calc_WodaFuchs2008(obj))
```
In other words, with my approach we don't change the expectation of that test.
> Make calc_WodaFuchs2008() work on more RLum.Results objects

- R/Risoe.BINfileData2RLum.Data.Curve.R
- tests/testthat/test_Risoe.BINfileData2RLum.Data.Curve.R
If `id` is not passed as an argument, the function tries to resolve it by using the `pos`, `run` and `set` arguments, but this error would occur:
```R
.Risoe.BINfileData2RLum.Data.Curve(CWOSL.SAR.Data, pos = 1, set = 2, run = 1)
```
As `METADATA` is converted from data.frame to a list a few lines before, it cannot be accessed any longer with the data.frame indexing, but is should use the standard list accessor.
This was an ancient bug introduced in bb8cf69, but totally harmless since it's in an internal function that is never called without the `id` argument.
> Make .Risoe.BINfileData2RLum.Data.Curve() work without the id argument

- NEWS.Rmd
- NEWS.md
- R/read_BIN2R.R
- tests/testthat/test_read_BIN2R.R
The relevant changes are the addition of the two `if`s and the change to `n = max(0, temp.LENGTH - 4)` to avoid `n` going negative (similarly to what was already existing for versions 6, 7, 8). Fixes #225.
> Make read_BIN2R() not crash when forcing a version on an empty file

- NEWS.Rmd
- NEWS.md
- R/extract_IrradiationTimes.R
- tests/testthat/test_extract_IrradiationTimes.R
This moves an existing check a few lines up. The actual change is quite small, but there is a lot of indentation changes because I removed a duplicated `if(!missing(file.BINX))` check inside a block that had already checked for that. Fixes #228.
> Improve consistency check in extract_IrradiationTime()

- NEWS.Rmd
- NEWS.md
- R/plot_Histogram.R
- tests/testthat/test_plot_Histogram.R
Fixes the crash reported in #186. However, the graph doesn't appear interactive at all (I checked with RStudio).
> Fix crash when using interactive mode for plot_Histogram()

- R/addins_RLum.R
- R/install_DevelopmentVersion.R
This excludes the bodies of `addins_RLum()` and `install_DevelopmentVersion()` from coverage as they cannot be tested with testthat (part of #121).
> Exclude untestable functions from coverage

- R/calc_MinDose.R
- tests/testthat/test_calc_MinDose.R
This makes it fail much faster when a converging fit for the profile log-likelihood cannot be found. Fixes #234.
> Don't use the bbmle::profile() try_harder option in calc_MinDose()

- .github/workflows/R-CMD-check.yml
> Remove the windows-2019 (oldrel) instance from the CI actions

- tests/testthat/_snaps/analyse_SAR.TL.md
- tests/testthat/setup.R
- tests/testthat/test_analyse_SAR.TL.R
This adds some snapshot tests for `analyse_SAR.TL()`, as I'm working on some changes to that function, and luckily there are just a few tests.
I've written the `expect_snapshot_RLum()` helper as we have to ignore the `.uid` and `.pid` fields, which would never match. The expected output is saved in the `tests/testthat/_snaps/analyse_SAR.TL.md` and contains a JSON representation of the output `RLum.Results` object.
We need to see how CI reacts to that, there may be tolerances that need to be set to satisfy different machine configurations. :crossed_fingers: 
This is the start of #243.
> Add the expect_snapshot_RLum() test helper and start using it

- NEWS.Rmd
- NEWS.md
- R/analyse_SAR.TL.R
- tests/testthat/_snaps/analyse_SAR.TL.md
This addresses all correctness issues pointed out in #245. Having the snapshot was invaluable to find the problems, and now it makes it visually easier to see what has actually changed.
Much of this code is overly complicated, but I'm cleaning it up separately. 
Note: I've used `NA_real_` and `NA_character_` as I'm going to use `data.table` to simplify it, and for that it really matter that the column have the correct type, otherwise it's not possible to bind them together.
Fixes #245.
> Correct the rejection.criteria data frame created by analyse_SAR.TL()

- DESCRIPTION
- R/RLum.Analysis-class.R
- R/RLum.Data.Curve-class.R
- R/internals_RLum.R
- R/plot_NRt.R
- R/plot_RLum.Analysis.R
- R/plot_RLum.Data.Curve.R
- man/RLum.Analysis-class.Rd
- man/RLum.Data.Curve-class.Rd
- man/plot_NRt.Rd
- man/plot_RLum.Data.Curve.Rd
- tests/testthat/test_internals.R
`zoo::rollmean()` and `zoo::rollmedian()` can be almost directly replaced by `data.table::frollmean()` and `data.table::frollapply()`. The main difference between the two sets of functions is in the default arguments:
- `k` in `rollmedian()` has to be odd for zoo (it throws a warning otherwise), but can be even for data.table
- `align` defaults to "center" for zoo, but to "right" for data.table
- `fill` defaults to NULL for zoo (meaning no filling, so the result vector can be shorter than the input), but to NA for data.table
Given that `.smoothing()` (the main user of these functions) always sets explicitly these values, there is no actual difference between the behaviour of the two packages when called via `.smoothing()`.
However, to replicate the existing behaviour, a few direct calls …
> Remove the dependency on the zoo package

- NEWS.Rmd
- R/plot_RLum.Data.Curve.R
- man/plot_RLum.Data.Curve.Rd
- tests/testthat/test_plot_RLum.Data.Curve.R
This now returns an error when an incorrect value is provided instead of silently skipping curve normalisation. Docs have been also clarified a bit. Fixes #250.
> Validate the norm argument in plot_RLum.Data.Curve()

- NEWS.Rmd
- R/analyse_pIRIRSequence.R
- tests/testthat/test_analyse_pIRIRSequence.R
The function doesn't skip plotting anymore if the device size is too small but `plot.single = FALSE`. This recovers the coverage lost in `analyse_pIRIRSequence.R` and adds some more tests to further increase it. Fixes #253.
> Increase coverage in analyse_pIRIRSequence.R

- R/analyse_baSAR.R
- tests/testthat/test_analyse_baSAR.R
This fixes the first example from #273 and adds tests for the other 2 examples ([adjusted according to this comment](https://github.com/R-Lum/Luminescence/issues/273#issuecomment-2383461298)). The rest of the commits (best looked at one by one) are code consolidation and some additional tests that should increase coverage over 90% for this file.
Fixes #273.
> Don't fail in analyse_baSAR() if no record is selected and other code cleanup

- NEWS.Rmd
- R/analyse_FadingMeasurement.R
- tests/testthat/test_analyse_FadingMeasurement.R
We stop early if the `RLum.Analysis` input object originated from a BIN-file with version older than 05, as that's the version that introduced the `TIMESINCEIRR` field being used in the function.
Fixes #281.
> Fix crash in analyse_FadingMeasurement() with BIN version older than 05

- NEWS.Rmd
- R/analyse_FadingMeasurement.R
- tests/testthat/test_analyse_FadingMeasurement.R
This addresses a number of small issues revealed by the example from #283 as well as the main crash. Fixes #283.
> Fix crash in analyse_FadingMeasurement() on an RLum.Analysis object with plot = TRUE

- NEWS.Rmd
- R/calc_Lamothe2003.R
We could not find a justification for the presence of the `(1/Fading_C -1)` term and reverted to a more mathematically obvious formulation of the error term. Fixes #96.
> Remove unexplained term from error calculation in calc_Lamothe2003()

- R/read_XSYG2R.R
- man/read_XSYG2R.Rd
- tests/testthat/_snaps/plot_GrowthCurve.md
- tests/testthat/setup.R
- tests/testthat/test_plot_GrowthCurve.R
One test involving method `QDR` with `mode = "extrapolation"` could not be turned into a snapshot test, I'll investigate that later so see why that should be the case.
Part of #143.
> Add snapshot tests for plot_GrowthCurve()

- tests/testthat/_snaps/plot_GrowthCurve.md
- tests/testthat/setup.R
- tests/testthat/test_plot_GrowthCurve.R
While we use R 4.3.3 in CI, we remove those values from the snapshot, so we can run those tests on all Linux versions as well as getting coverage from them. Fixes #312.
> Adapt the plot_GrowthCurve() snapshot tests to run on R 4.3.3

- R/fit_DoseResponseCurve.R
- man/fit_DoseResponseCurve.Rd
- tests/testthat/_snaps/fit_DoseResponseCurve.md
This is in preparation for further changes coming in #319.
> Store the fit_DoseResponseCurve() arguments in RLum.Results

- R/fit_DoseResponseCurve.R
This makes the inner function's formal arguments identical across all definitions, although in case being modified in this patch the `x` argument is ignored. My hope is to eventually come up with a better overall solution. Fixes #323.
> Resolve note about multiple local function definitions

- R/RLum.Analysis-class.R
- R/RLum.Data.Curve-class.R
- R/RLum.Data.Image-class.R
- R/RLum.Data.Spectrum-class.R
- tests/testthat/test_RLum.Data.Curve.R
- tests/testthat/test_RLum.Data.Image.R
- tests/testthat/test_RLum.Data.Spectrum.R
Fixes the two crashes, adds the coercion functions between `list` and `RLum.Data.Spectrum`, and adds some newline when showing those objects. Fixes #326.
> Don't crash when coercing an empty list to RLum.Data objects

- R/read_BIN2R.R
- man/read_BIN2R.Rd
This changes the way we build the final metadata table: rather than first allocating space for an empty `data.table` and then modify it at each iteration, we create a list of lists corresponding to each row and call `rbindlist()` on it at the end.
This provides a massive speed up: the time to read a 46MB file, goes from ~33s to ~15s.
I've left a FIXME note, as in the previous code the `EXTR_START` and `EXTR_END` fields (although they were read), were not assigned, so they picked up their default value (0). To reproduce exactly the previous results, I'm doing the same here, but I'm not sure if this is correct, so we may want to revisit it.
This is clearer to review by looking at the single commits, the speed up being contained in the first. Part of #298.
> Speed up the reading of BIN/BINX files

- R/read_BIN2R.R
This avoids calling `readBin()` and then discarding its result. Fixes #334.
> Use seek() to move forward in the connection in read_BIN2R()

- R/fit_DoseResponseCurve.R
- R/plot_DoseResponseCurve.R
- tests/testthat/_snaps/analyse_SAR.CWOSL.md
- tests/testthat/_snaps/fit_DoseResponseCurve.md
- tests/testthat/test_fit_DoseResponseCurve.R
This allows to produce correct plots in the extrapolation case, where `De` can be negative. Fixes #340.
> Return also the computed De without abs() from fit_DoseResponseCurve()

- NEWS.Rmd
- R/read_BIN2R.R
- tests/testthat/test_read_BIN2R.R
If records are not read because n.records is set by the user, the record ID will not be sequential starting from 1, and thus cause problems elsewhere. Fixes #343.
> Always recompute the record index at the end of read_BIN2R()

- NEWS.Rmd
- R/read_BIN2R.R
- tests/testthat/test_read_BIN2R.R
> Update the .RESERVED slot when records are dropped in read_BIN2R()

- R/read_BIN2R.R
This removes the need for `rbindlist()` at the end, and thus it allows to avoid the allocation of some columns that can be easily derived from others.
This produces a reproducible speed up of at least 1s on the 46MB test file, in some cases up to 5s (perhaps depending on garbage collection). Part of #298.
This also fixes #336 and fixes #356.
> Create the METADATA data.table by columns instead of by rows

- R/read_BIN2R.R
- tests/testthat/test_Risoe.BINfileData2RLum.Analysis.R
- tests/testthat/test_read_BIN2R.R
This ensures that we return an object that is recognised to be empty (`set_Risoe.BINfileData()`), rather than objects with all fields set to 0. Fixes #346.
This also removes a block of code that had become unreachable after the changes in 58c2c23, and  consolidates the text of two messages.
> Return empty objects from read_BIN2R() when no records are kept

- R/read_BIN2R.R
- tests/testthat/test_plot_ROI.R
This avoids some duplicated work and duplicated printouts of the same message. Fixes #362.
> Recalculate the record index only once at the end of read_BIN2R()

- NEWS.Rmd
- R/verify_SingleGrainData.R
- tests/testthat/test_verify_SingleGrainData.R
> Don't let verify_SingleGrainData() crash on an empty list input

- R/analyse_IRSAR.RF.R
- tests/testthat/test_analyse_IRSAR.RF.R
> Check if the originator is not NA before using it in a comparison

- R/analyse_IRSAR.RF.R
- tests/testthat/test_analyse_IRSAR.RF.R
As `method.control` is already given as a list and it's unlikely we want to support applying different algorithmic parameters to different aliquots, in the self-call we pass it directly, without further listifying it. I've checked all other uses we have of `method.control` and indeed this was the only case.
This is a regression that was introduced in f0d075275, and was first noticed in #372.
> Don't listify the method.control argument when the input object is a list

- R/analyse_IRSAR.RF.R
- src/src_analyse_IRSARRF_SRS.cpp
This cleans up a bit the code and provides some speed up. Part of #372.
In the example that you gave me I went from 54.6s to 29.2s on average. I've been measuring time using just 1 core with `-O3` optimization to better see the differences: savings using multiple cores when doing the MC iterations will be much smaller. Also, performance changes may be affected by processor type and compiler used.
I've tried a bunch of other things that seemed at first positive changes, but that measured on an optimized build do not actually provide any gain.
> improve performance of src_analyse_IRSARRF_SRS()

- NEWS.Rmd
- src/src_analyse_IRSARRF_SRS.cpp
- tests/testthat/test_analyse_IRSAR.RF.R
These changes improve the running time of our example when using -O2, which is the default compilation flag on CRAN. This is a mild regression for the -O3 flag, but given that hardly anybody will use that, the compromise seems worth it. Part of #372.
Single core performance using 3 slide windows:
- with -O2 time goes from 13.5s to 10.7s
- with -03 time goes from 10.1s to 10.7s
Single core performance using 10 slide windows:
- with -O2 time goes from 40.9s to 32.6s
- with -03 time goes from 29.1s to 32.5s
> Improve performance of src_analyse_IRSARRF_SRS() with optimization at -O2

- NEWS.Rmd
- R/analyse_baSAR.R
- tests/testthat/test_analyse_baSAR.R
Now we don't let the thinning interval exceed `n.MCMC / 2`, so that we are certain to get at least two posterior samples: with that we don't crash anymore and JAGS doesn't print out ugly errors shows in the issue. Fixes #407.
> Fix crash in analyse_baSAR() if n.MCMC is equal to the thinning interval

- R/calc_EED_Model.R
- man/calc_EED_Model.Rd
- tests/testthat/test_calc_EED_Model.R
This adds some `nocov` blocks around functions that are not called, and removes a duplicate copy of `.Initial_State_of_OSL()`. Fixes #404.
> Clean up calc_EED_Model() and increase coverage

- R/analyse_Al2O3C_Measurement.R
- R/calc_FastRatio.R
- R/calc_Huntley2006.R
- R/internals_RLum.R
- R/methods_DRAC.R
- R/plot_Histogram.R
- R/plot_KDE.R
- R/plot_RadialPlot.R
- tests/testthat/test_analyse_Al2O3C_Measurement.R
- tests/testthat/test_calc_FastRatio.R
- tests/testthat/test_calc_Huntley2006.R
- tests/testthat/test_internals.R
- tests/testthat/test_methods_DRAC.R
- tests/testthat/test_plot_Histogram.R
- tests/testthat/test_plot_KDE.R
- tests/testthat/test_plot_RadialPlot.R
This adds the `.validate_length()` helper: at the moment it can only be used to validate an exact length (`==`), but I may extend it at some point to allow checking for `>=` or `<=`
> Add an internal helper function to validate the expected length of an input

- R/RLum.Analysis-class.R
- R/analyse_Al2O3C_Measurement.R
- R/analyse_FadingMeasurement.R
- R/analyse_IRSAR.RF.R
- R/analyse_SAR.CWOSL.R
- R/analyse_baSAR.R
- R/analyse_pIRIRSequence.R
- R/calc_AverageDose.R
- R/calc_WodaFuchs2008.R
- R/calc_gSGC_feldspar.R
- R/extract_IrradiationTimes.R
- R/fit_DoseResponseCurve.R
- R/fit_LMCurve.R
- R/fit_OSLLifeTimes.R
- R/fit_SurfaceExposure.R
- R/fit_ThermalQuenching.R
- R/import_Data.R
- R/internals_RLum.R
- R/plot_AbanicoPlot.R
- R/plot_DoseResponseCurve.R
- R/plot_RLum.Data.Spectrum.R
- R/read_BIN2R.R
- R/read_RF2R.R
- R/read_SPE2R.R
- R/read_XSYG2R.R
- tests/testthat/test_calc_AverageDose.R
- tests/testthat/test_convert_XSYG2CSV.R
- tests/testthat/test_fit_LMCurve.R
- tests/testthat/test_read_XSYG2R.R
This is not meant to replace all uses of `message()`, but only those that refer to an error condition, as it prepends the `Error:` string to the message reported. Fixes #422.
> Introduce the .throw_message() helper

- NEWS.Rmd
- R/calc_IEU.R
- tests/testthat/test_calc_IEU.R
These are mainly bandaid fixes: presumably there is a better way to identify numerical errors or wrong settings before it's too late, but I don't know the details of algorithm. Fixes #424.
> Fix various crashes in calc_IEU() 

- NEWS.Rmd
- R/fit_DoseResponseCurve.R
- man/fit_DoseResponseCurve.Rd
- tests/testthat/test_fit_DoseResponseCurve.R
This makes the function accept a list of data frames as input, in which case it calls itself on each element of the list and produces a list of `RLum.Results` as output. Fixes #405.
> Make fit_DoseResponseCurve() accept a list as input

- NEWS.Rmd
- R/use_DRAC.R
This increases the randomness in the names ensuring that they are unique without generating on obvious pattern. Instead of appending a sequential numerical value, we append a unique random integer so that we don't make the pattern so obvious (it's probably not not discoverable at all, but who knows for sure). Uniqueness is enforced by the fact that we sample over all numbers from 0 to 9999, which is enough as we accept a maximum of 5000 inputs.
> Make the pattern in the identifiers submitted to DRAC not discoverable

- NEWS.Rmd
- R/trim_RLum.Data.R
- man/trim_RLum.Data.Rd
- tests/testthat/test_trim_RLum.Data.R
This fixes the 3 crashes mentioned in #460 plus a 4th one:
- crash if the `Lum.Analysis` object contained `RLum.Data.Spectrum` data
- crash if two negative indices were provided in `trim_range` (bonus fix!)
- crash if the indices where given in non-increasing order and the first exceeded the bounds of the object
- crash when using `trim_range` on an `RLum.Data.Image` object
Fixes #460.
> Fix crashes in trim_RLum.Data() caused by misspecifications in trim_range

- R/analyse_IRSAR.RF.R
- man/analyse_IRSAR.RF.Rd
- tests/testthat/_snaps/analyse_IRSAR.RF.md
- tests/testthat/test_analyse_IRSAR.RF.R
This was effectively available before the changes in 51c324bd5 made the validation of the `method` argument stricter and made this feature unavailable (also causing a loss in coverage).
> Add explicit support for disabling the fitting in analyse_IRSAR.RF()

- R/RLum.Analysis-class.R
- R/analyse_SAR.TL.R
- R/plot_NRt.R
- man/RLum.Analysis-class.Rd
- tests/testthat/_snaps/plot_NRt.md
- tests/testthat/test_analyse_SAR.TL.R
- tests/testthat/test_plot_NRt.R
> Improve validation against a list of RLum.Analysis objects

- NEWS.Rmd
- NEWS.md
- R/analyse_baSAR.R
- tests/testthat/test_analyse_baSAR.R
There were four different bugs, each one fixed in its own commit. Fixes #521.
> Fix crashes and messages when setting `variable.names` in analyse_baSAR()

- R/plot_RLum.Results.R
- tests/testthat/test_plot_RLum.Results.R
This also fixes an error when plotting an object produced by `analyse_IRSAR.RF()` as it was matching a mistyped originator.
> Increase coverage in plot_RLum.Results.R

- NEWS.Rmd
- NEWS.md
- R/calc_Huntley2006.R
> Plot the natural curve for extrapolation also in the negative quadrant

- R/fit_IsothermalHolding.R
- tests/testthat/test_fit_IsothermalHolding.R
This is necessary as the BTS model uses `integrate()`, and in order to retrieve its result one needs to extract `$value` from the object it returns. But this confuses `nlsLM()` into thinking that `value` is a parameter to be optimized and for which a starting point should be given.
The only workable solution seems to hide all that complexity into a wrapper function (`f_BTS)` that is used as right-hand side in the formula. Because of this, we need to reformulate also `f_GOK` as a function.
Due to R's abstruse way of accessing variables in the environment from inside a function, it turns out that we can access `rhop` but not `isoT`, so we have to add `isoT` to the model signatures and also to the `data` argument.
This commit also introduces some changes to the BTS model: in particular we …
> fit_IsothermalHolding(): define the models as functions rather than strings

- R/analyse_ThermochronometryData.R
- R/fit_IsothermalHolding.R
- man/fit_IsothermalHolding.Rd
- tests/testthat/test_analyse_ThermochronometryData.R
- tests/testthat/test_fit_IsothermalHolding.R
By default this tests 1000 random values for the `s` parameter instead of optimizing it, as @RLumSK  found it to be practically the only way to get this model to fit.
For tests to run in a reasonable time I've added a "hidden" argument `num_s_values_bts` to be able to change the default from 1000 values to something much smaller. We could expose that later.
> Improve fitting of the BTS model in fit_IsothermalHolding()

- R/analyse_SAR.CWOSL.R
The interaction of the various plot options between `analyse_pIRIRSequence()`, `analyse_SAR.CWOSL()`, `plot_DoseResponseCurve()` is quite intricate. For example, the `plot_singlePanels` option is just a logical in `analyse_pIRIRSequence()` and `plot_DoseResponseCurve()`, but can accept integer values in `analyse_SAR.CWOSL()`. The latter also has a `plot_onePage` option which is largely overlapping (but not totally) with `plot_singlePanels`.
In any case, from my testing this PR fixes the problem without regressing `analyse_SAR.CWOSL()`. No NEWS as the regression occurred on the development version.
Fixes #572.
> Fix single page layout of SAR.CWOSL plots from analyse_pIRIRSequence()

- NEWS.Rmd
- NEWS.md
- R/plot_RLum.Analysis.R
The issue seems to be that setting `mfrow` resets the `par` settings (as the pre-existing comment stated) even in the case when `mfrow` is not actually changed. Therefore, we cannot have a shared par.default for the two cases of `plot_singlePanels`, but each must define its own.
This fixes a regression introduced in 9f5a918. Fixes #589.
> Fix regression in plot generated by analyse_FadingMeasurement()

- NEWS.Rmd
- NEWS.md
- R/calc_CosmicDoseRate.R
- tests/testthat/test_calc_CosmicDoseRate.R
This fixes #595 and adds some more validation of inputs to cover other corner cases.
The code for the case in which `length(depth) == 1` can be removed because after validation it must be that also `length(density) == 1`: note that the computation done in that block is undone and then recomputed in the second block, as it's also true that `length(depth) == length(density)`. So we may as well just use the code in the second block in both cases.
> Tighten checks on inputs and consolidate code in calc_CosmicDoseRate()

- NEWS.Rmd
- NEWS.md
- R/calc_FadingCorr.R
- man/calc_CosmicDoseRate.Rd
- man/calc_FadingCorr.Rd
- tests/testthat/test_calc_FadingCorr.R
> Improve validation and documentation of calc_FadingCorr() arguments

- NEWS.Rmd
- NEWS.md
- R/RLum.Analysis-class.R
- tests/testthat/test_RLum.Analysis-class.R
> Don't crash when sorting an empty RLum.Analysis object

- .github/workflows/R-CMD-check.yml
This workflow at the moment never completes. This is caused by `devel` now pointing to R 4.6, and this leads to try to read some inexistent path from the package repository:
https://cran.rstudio.com/bin/windows/contrib/4.6/PACKAGES.gz
We should reenable it when the link above starts working, presumably early next week.
> Disable the windows-latest devel workflow

- R/analyse_FadingMeasurement.R
- tests/testthat/test_plot_RLum.R
- tests/testthat/test_plot_RLum.Results.R
The changes in #637 have actually lost 2 lines of coverage. The changes in #617 caused 2 other lines not to be covered anymore, and I could not find a way to reach them: I suppose that the early returns added in that PR have made this block of code as unreachable, so I've marked it as `nocov`.
> Recover a few lines of lost coverage

- NEWS.Rmd
- NEWS.md
- R/plot_KDE.R
- tests/testthat/_snaps/plot_KDE/kde-summary-left.svg
- tests/testthat/_snaps/plot_KDE/kde-summary-sub.svg
- tests/testthat/test_plot_KDE.R
This fixes a regression from f8fc07b. Fixes #642.
This also adds a missing newline when `in.2s` is one of the summary statistics selected.
> Fix positioning of the summary table in plot_KDE()

- tests/testthat/test_plot_AbanicoPlot.R
- tests/testthat/test_plot_DRTResults.R
- tests/testthat/test_plot_Histogram.R
- tests/testthat/test_plot_KDE.R
- tests/testthat/test_plot_RadialPlot.R
This should speed up a bit the total time for running tests without losing any coverage. Many of these had to do with adding coverage for the various positioning of the summary boxes, but with the code consolidation done in #291 they are no longer necessary.
> Remove redundant tests

- R/calc_Huntley2006.R
… try again with a different approach. No NEWS, no additional tests
+ up x-axis labelling; we use rectangle parentheses
@mcol This also avoids the super large error range for the simulated curve in the plot output and it could run all samples here correctly.
> Adjust #660 because the search range was too vast

- NEWS.Rmd
- NEWS.md
- R/scale_GammaDose.R
- man/scale_GammaDose.Rd
- tests/testthat/_snaps/scale_GammaDose/defaults.svg
- tests/testthat/test_scale_GammaDose.R
When in eef9aa5 the `plot_single` argument was renamed to `plot_singlePanels`, it was noted that the option behaved in the opposite way. However, only its default value was changed but not the actual implementation. This now makes the argument work as expected and conforming to other functions.
Fixes #698.
> Make the plot_singlePanels argument of scale_GammaDose() work as expected

- NEWS.Rmd
- NEWS.md
- R/calc_FiniteMixture.R
This is ensured by adding two extra points to the polygons corresponding to the base of the density.
Fixes #706.
> Don't leave unfilled areas in the density plots in calc_FiniteMixture()

- NEWS.Rmd
- NEWS.md
- R/calc_FiniteMixture.R
- man/calc_FiniteMixture.Rd
This adds some more configuration option and fixes the case when non-consecutive number of components are requested (such as `n.components = c(2, 5)`).
Fixes #717.
> Make the calc_FiniteMixture() plots more customizable.

- NEWS.Rmd
- NEWS.md
- R/calc_FiniteMixture.R
Now we always do a plot, but if we have thrown a warning because the results contained `NA` values, we show that in the plot subtitle, so that the user doesn't forget about the warning.
Fixes #718.
> Plot results even when NAs are produced in calc_FiniteMixture()

- NEWS.Rmd
- NEWS.md
- R/calc_MinDose.R
- R/plot_RLum.Results.R
- tests/testthat/test_calc_MinDose.R
This replaces a bunch of ugly warnings that would be throw by `simpleLoess()` with an actionable warning from `calc_MinDose()`.
Fixes #721.
> Warn if loess fitting cannot be done as there are not enough data

- NEWS.Rmd
- NEWS.md
- R/calc_Huntley2006.R
- tests/testthat/test_calc_Huntley2006.R
> Don't crash if all simulated Lx/Tx values are identical

- NEWS.Rmd
- NEWS.md
- R/plot_DetPlot.R
- tests/testthat/test_plot_DetPlot.R
Locally the tests pass but I cannot get `covr::file_coverage()` on the multicore test (the same error occurred before even without code changes, just we didn't have test that set that option). Perhaps on CI coverage will run correctly, let's see!
Fixes #742.
> Improve the logic for the multicore argument in plot_DetPlot()

- NEWS.Rmd
- NEWS.md
- R/plot_Histogram.R
- man/plot_Histogram.Rd
- tests/testthat/test_plot_Histogram.R
The right margin can be smaller when errors are not plotted, as there is no need to leave space for the standard error axis.
Fixes #748.
> Reduce the right margin in plot_Histogram() if errors are not plotted

- NEWS.Rmd
- NEWS.md
- R/fit_EmissionSpectra.R
- man/fit_EmissionSpectra.Rd
- tests/testthat/test_fit_EmissionSpectra.R
This avoids a crash when working on a frame with only negative counts after background subtraction, which by default get replaced by zeros.
Fixes #761.
> Don't normalise data if all values are zero

- NEWS.Rmd
- NEWS.md
- R/plot_DRTResults.R
- tests/testthat/test_plot_DRTResults.R
> Fix crash in plot_DRTResults() when drawing the polygon if all preheat values are identical

- R/plot_DRTResults.R
- tests/testthat/test_plot_DRTResults.R
With this, it's not a problem anymore to indicate more preheat temperatures than De values, as the entries in excess are ignored. This reduces errors in RLumShiny when a user inputs the secondary dataset manually and this dataset has fewer entries than the primary one.
Fixes #771.
> Relax check on the number of preheat temperatures

- NEWS.Rmd
- NEWS.md
- R/plot_DoseResponseCurve.R
- man/plot_DoseResponseCurve.Rd
- tests/testthat/_snaps/plot_DoseResponseCurve/extrapolation-gok.svg
- tests/testthat/_snaps/plot_DoseResponseCurve/log-xy.svg
- tests/testthat/test_plot_DoseResponseCurve.R
This allows to specify a logarithmic transformation if the fit object had mode other than `"extrapolation"`.
Note that the change the `extrapolation-gok` happened only because its model is fitted much earlier, so the random values used in the MC runs are different.
Fixes #820.
>  Add support for log transformation in plot_DoseResponseCurve()

- R/analyse_IRSAR.RF.R
- R/analyse_SAR.TL.R
- R/analyse_baSAR.R
- R/analyse_portableOSL.R
- R/calc_CentralDose.R
- R/calc_MinDose.R
- R/calc_WodaFuchs2008.R
- R/convert_Concentration2DoseRate.R
- R/convert_Wavelength2Energy.R
- R/extract_IrradiationTimes.R
- R/fit_DoseResponseCurve.R
- R/fit_LMCurve.R
- R/fit_SurfaceExposure.R
- R/internals_RLum.R
- R/merge_Risoe.BINfileData.R
- R/plot_AbanicoPlot.R
- R/plot_DetPlot.R
- R/plot_GrowthCurve.R
- R/plot_RLum.Data.Spectrum.R
- R/read_BIN2R.R
- R/read_PSL2R.R
- R/read_XSYG2R.R
- R/verify_SingleGrainData.R
- R/write_RLum2CSV.R
- tests/testthat/test_convert_Wavelength2Energy.R
- tests/testthat/test_internals.R
- tests/testthat/test_merge_Risoe.BINfileData.R
- tests/testthat/test_plot_AbanicoPlot.R
- tests/testthat/test_plot_RLum.Data.Spectrum.R
This adds the 'error' argument, with `TRUE` as default value. When it is set to `FALSE`, the message is reported without having "Error: " prepended to it, which allows us to use .throw_message() a bit more often.
> Add more flexibility to the message reported by .throw_message()

- NEWS.Rmd
- NEWS.md
- R/trim_RLum.Data.R
- tests/testthat/test_trim_RLum.Data.R
> Don't crash if both trim_range values exceed the number of channels

- R/plot_AbanicoPlot.R
- tests/testthat/_snaps/plot_AbanicoPlot/default.svg
- tests/testthat/_snaps/plot_AbanicoPlot/dispersion-error-bars.svg
- tests/testthat/_snaps/plot_AbanicoPlot/dots-cex.svg
- tests/testthat/_snaps/plot_AbanicoPlot/line-frame-legend-rotated.svg
- tests/testthat/_snaps/plot_AbanicoPlot/line-frame-legend.svg
- tests/testthat/_snaps/plot_AbanicoPlot/rotated.svg
This fixes a regression introduced in 66a21349. Only the two snapshots with `log.z = FALSE` have a visible improvement, the others have only an almost imperceptible change
Fixes #877.
> Fix z-axis ticks and labels if log.z = FALSE

- R/plot_NRt.R
- tests/testthat/test_plot_NRt.R
This also adds support for lists of data.frames or matrices, as according to the docs they are supported.
Fixes #893.
> Improve validation against lists of length 2

- R/internals_RLum.R
- tests/testthat/test_internals.R
For example, a matrix has classes "matrix" and "array".
Fixes #907.
> Don't assume that class always returns a single value in .rm_nonRLum()

- R/report_RLum.R
- tests/testthat/test_report_RLum.R
The function is supposed to produce a vector of length at least 2, for the way it's used downstream. Therefore, if the input has dimension of length less than 2, we pad it with zeros.
Fixes #938.
> Compute the correct dimension in report_RLum()

- NEWS.Rmd
- NEWS.md
- R/plot_Risoe.BINfileData.R
- tests/testthat/_snaps/plot_Risoe.BINfileData/tl.svg
This also ensures that if a custom temperature label is specified, this is used in both the x and y axes.
Fixes #971.
> Fix x-axis label for TL plots in plot_Risoe.BINfileData()

- .github/workflows/test-coverage.yml
The `test-coverage` workflow reports these messages:
```
find: ‘/home/runner/work/_temp/package’: No such file or directory
Warning: No files were found with the provided path: /home/runner/work/_temp/package. No artifacts will be uploaded.
```
This means that in case of an error, it's not possible to download the artifacts produced on the CI machines. Perhaps this will fix it.
> Try to get debug info from coverage runs

- NEWS.Rmd
- NEWS.md
- R/fit_EmissionSpectra.R
- R/fit_OSLLifeTimes.R
> Use the correct screen indices reported by split.screen()

- DESCRIPTION
- NEWS.Rmd
- NEWS.md
- R/internals_RLum.R
- tests/testthat/test_internals.R
Fixes #1009 and allow us to remove our own definition of `%||%` since it's already defined from R 4.4.
> Increase the minimum R version supported to 4.4

- NEWS.Rmd
- NEWS.md
- R/install_DevelopmentVersion.R
- man/install_DevelopmentVersion.Rd
This removes the use of the deprecated `github_branches()` and removes some code duplication.
Fixes #1079.
> Refactor install_DevelopmentVersion()
